SWYP-team-2th/client

.github/workflows/test-check.yml
* CI 단계에서 테스트 빌드가 성공하는지 체크하는 워크플로우를 추가합니다.
| Issue     |    #20    |
---
* yml 파일 작성
* 의존성 설치했을 때, yarn.lock의 변경이 없으면, 기존 캐싱된 패키지를 그대로 사용하도록 했습니다.
@Jeongchanyeong 빌드 워크플로우 추가할 때도 요거 확인해주세요~~!!
---
close #20 
---
=> test check 워크플로우를 추가한다.

src/api/__tests__/config.test.tsx, tsconfig.app.json, tsconfig.node.json
* 빌드가 깨지는 문제를 해결합니다.
| Issue     |   #38     |
---
* noFallthroughCasesInSwitch 이런 옵션이 없는데 사용하고 있어서 제거
* tsBuildInfoFile 옵션을 사용하기 위해 incremental 옵션이 추가로 켜져야함
---
close #38 
---
=> 빌드가 깨지는 문제를 해결한다.

.github/workflows/build-check.yml, .github/workflows/lint-check.yml, src/utils/cn/index.ts
| Issue     |   #5    |
---
* PR 단계에서 자동으로 코드 스타일 & 빌드 검증 진행
* Lint 오류가 있는 경우 미리 감지하여 코드 품질 유지
* 배포의 경우 추후 진행 예정
---
close #5 
---
=> Lint Check & Build Check 워크플로우 세팅

.github/workflows/storybook-build-check.yml, .gitignore, .storybook/main.ts, .storybook/preview.ts, package.json, src/components/__tests__/templates/Component.stories.tsx, src/components/__tests__/templates/Component.template.tsx, yarn.lock
* 스토리북 사용을 위해 필요한 패키지들을 설치합니다.
* 스토리북 빌드 체크하는 워크플로우를 추가합니다.
* 스토리북 컨벤션을 위해 템플릿 코드를 작성합니다. (단순 예시입니다.)
| Issue     |   #43     |
---
* 스토리북 사용 설명을 위해 `src/component/__tests__` 하위에 템플릿 코드들을 작성합니다.
* 해당 컴포넌트는 실제로 사용하지 않습니다.
* `Component.stories.tsx`에 주석과 함께 자세한 설명을 작성했습니다.
---
close #43 
---
=> 스토리북 초기 환경 세팅

.github/workflows/git-push.yml, build.sh, yarn.lock
* vercel 배포를 무료로 하기 위한 작업을 진행합니다.
| Issue     |    #46    |
---
* develop, main에 머지되면, 포크 뜬 레포에도 반영되도록 워크플로우 작성
---
close #46 
---
=> build.sh 파일과 원격 레포 push 워크플로우를 추가한다.

.github/workflows/git-push.yml
* git push yml 파일 워크플로우가 실패한다.
| Issue     |  #48      |
---
* 깃헙 아이디, 레포명이 제대로 들어가있지 않음.
* 수정한다.
---
close #48 
---
=> git push yml 파일을 수정한다.

.github/workflows/git-deploy.yml
prod, dev 배포 워크플로우 작성 완료.
| Issue     |    #41 #42    |
---
main과 dev 브랜치에서 자동으로 Vercel에 배포되도록 설정하였습니다.
close #41 #42 
---
=> prod, dev 배포 워크플로우 작성

.github/workflows/git-deploy.yml
배포 브랜치 명 잘못 기입
| Issue     |     #42   |
---
deploy branch명 dev -> develop로 수정
---
close #42 
---
=> develop 브랜치 deploy 오타 수정

.github/workflows/git-deploy.yml
Reverts SWYP-team-2th/client#51
=> Revert "develop 브랜치 deploy 오타 수정"

build.sh, package.json, vercel.json
* vercel에서 .storybook/main.ts ts 파일을 못 읽음
* 읽기위한 추가 설정을 해준다.
| Issue     |  #54      |
---
* 명령어 수정
* vercel.json 추가
---
close #54 
---
=> Vercel에 스토리북 배포를 하기 위한 세팅을 한다.

.gitignore
| Issue     |  #57      |
---
백엔드 서버 URL를 환경 변수로 관리하도록 세팅
---
`VITE_API_URL_DEV`
`VITE_API_URL_PROD` 
환경변수 사용하여 서버 URL 사용하심 됩니다.
close #57 
---
=> env 파일 추가 및 백엔드 서버 환경 변수 설정

src/index.css, tailwind.config.js
tailwind를 사용하여 디자인 시스템 토큰 값 세팅 (color, typography, spacing)
| Issue     |  #61 |
---
tailwind v4 적용 결과 @layer 객체 내부 클래스 명이 사용시에 Tailwind에서 자동완성이 되지 않는 문제점을 발견하였습니다.
이를 해결하기 위해 tailwind.config.js 파일 theme 내부에 변수 값들을 추가하였습니다.
v4 버전업이 된지 얼마 안 돼서 반영되지 않은 부분 같은데 다른 해결 방법이 있을지는 모르겠네요..!
---
`<div className="text-ts text-primary-300 pt-sm ">hi</div>`
text 및 color의 경우 위와 같이 사용하시면 됩니다.  spacing의 경우 tailwind의 기존 클래스와 동일하다면, 기존 tailwind 클래스 값으로 적용됩니다.
ex) rounded-sm (우리가 세팅한 spacing 값이 지정되지 않고 기존 tailwind 클래스 값 적용)
ex) text-sm (세팅한 spacing 값 적용)
추가적으로 반영할 필요가 있는 클래스나 속성이 있다면 피드백 부탁드립니다.
close #61 
---
=> design token custom

src/components/common/layout/DefaultLayout.tsx, src/components/common/layout/SubLayout.tsx, tailwind.config.js
| Issue     |    #68    |
---
1. DefaultLayout과 SubLayout을 분리 (1차 MVP에서 플로팅 버튼 있는 페이지와 없는 페이지에 따른 분리)
2. 화면 중앙 정렬
---
close #68 
---
=> layout setting

src/index.css, tailwind.config.js
| Issue     |  #72      |
---
디자인 시스템 변경사항 반영하였습니다.
typography system font 변경, 추가된 사항 반영
primary color 변경 반영
---
close #72 
---
=> 디자인 시스템 변경 사항 반영

package.json, src/components/common/button/Button.tsx, src/components/common/button/FloatingButton.tsx, yarn.lock
| Issue     | #63      |
---
Button 컴포넌트에서 두 방법중 하나 채택해서 pr 올립니다.
이전 방법은 경우의 수를 하나하나 대응해야 했는데 채택한 방법은 cn으로 병합하고 변수에 넣어 변환하여 className에 적용되도록 세팅하니 코드도 간결하고 유지보수에도 더 뛰어나더라구요.
사용 예시
`<Button buttonType="primary" size="lg" variant="outline">BUTTON</Button>`
`<Button buttonType="secondary" size="sm" variant="soild">BUTTON</Button>`
buttonType, size, variant에 지정된 값 props로 넘겨 사용하시면 됩니다.
`<FloatingButton buttonType="primary" size="sm">BUTTON</FloatingButton>`
`<FloatingButton buttonType="secondary" size="lg">BUTTON</FloatingButton>`
buttonType, size에 지정된 값 props로 넘겨 사용하시면 됩니다.
---
버튼 모두 잘 적용 되는 것까지 확인 완료하였습니다.
close #63 
---
=> 버튼 컴포넌트를 제작한다.

src/components/common/Button/FloatingButton.tsx
| Issue     |   #83     |
---
사진 확대 시에 존재하는 좋아요 플로팅 버튼 추가하였습니다.
네이밍은 제 3의 라는 뜻의 tertiary로 지정해놨는데, 다른 버튼 컬러 네이밍과의 조합이 어색하지 않다면 바로 머지해 주세요. 혹시 어색하다면 더 적절한 네이밍 추천 부탁드립니다.
---
close #83 
---
=> 추가된 버튼 디자인에 대응한다.

src/components/common/TextField/TextField.stories.tsx, src/components/common/TextField/TextField.tsx, src/components/common/TextField/index.ts, src/components/common/TextInput/TextInput.stories.tsx, src/components/common/TextInput/TextInput.tsx, src/components/common/TextInput/index.ts, src/index.css
* TextField 컴포넌트 작성
* color token 추가
* 스토리북 예시 작성
| Issue     | #81       |
---
* 차질이 생겨서 설계를 변경합니다.
* TextInput -> input 컴포넌트, 1줄 대응
* TextField -> textarea 컴포넌트, 여러줄 대응
* 스토리북 args로 사용법 확인해주시면 됩니다!
---
close #81 
---
=> TextField 컴포넌트를 작성한다.

src/components/common/TextField/TextField.stories.tsx, src/components/common/TextInput/TextInput.stories.tsx, src/components/common/Toast/Toast.tsx
=> Icon에 size option을 추가한다.

src/App.tsx, src/pages/OnBoarding/OnBoardingPage.tsx
| Issue     |   #94     |
---
UI 구현 진행중.
디자인 다 나오면 추가로 적용하겠습니다.
---
close #94 
---
=> 온보딩 페이지 UI를 구현한다.

src/components/common/Dialog/Dialog.stories.tsx, src/components/common/Dialog/Dialog.tsx, src/components/common/Dialog/DialogProvider.tsx, src/components/common/Dialog/hooks.ts, src/components/common/Dialog/index.ts, src/components/common/Overlay/Overlay.tsx, src/components/common/Overlay/index.ts, src/main.tsx
* Dialog 컴포넌트 제작
* Overlay 컴포넌트 제작
* 스토리북 예제 작성
| Issue     |   #87     |
---
* interface는 아래와 같습니다.
```tsx
interface DialogProps {
title: string; // 제목
description?: string; // 설명
cancelButtonProps?: { // 취소버튼 관련 props (optional)
text: string;
};
confirmButtonProps: { // 확인버튼 관련 props
text: string;
onClick: () => void;
};
showLaterButton: boolean; // 나중에 하기 버튼 노출 여부 props
}
```
* 사용법은 아래와 같습니다.
```tsx
const { openDialog, closeDialog } = useDialog();
// open 함수의 인자에는 Dialog 컴포넌트를 전달합니다.
openDialog(<SomeDialog />);
// close 함수는 그냥 호출합니다.
closeDialog();
```
스토리북 예제 보시면 이해 쉽게 되실거에요!
---
close #87 
---
=> Dialog 컴포넌트를 작성한다.

src/components/common/Header/Header.tsx
* 헤더 스타일을 변경한다.
| Issue     |   #117     |
---
* 좌, 우 노드에 너비를 지정해서 스타일이 깨지지 않도록 수정합니다.
---
close #117 
---
=> 헤더 스타일을 변경한다.

src/components/common/BottomSheet/BottomSheet.stories.tsx, src/components/common/BottomSheet/BottomSheet.tsx, src/components/common/BottomSheet/BottomSheetProvider.tsx, src/components/common/BottomSheet/hooks.ts, src/components/common/BottomSheet/index.ts, src/main.tsx
* BottomSheet 제작
* Provider 제작 및 연결
* 스토리북 예제 작성
| Issue     |   #111     |
---
* Dialog 사용법과 동일합니다!
* 컨텐츠는 사용하는 곳마다 상이하여 children으로 전달하는 방식으로 채택했어요!
---
close #111 
---
=> BottomSheet 컴포넌트를 제작한다.

src/api/useGetUserInfo.ts, src/api/useGetVoteList.ts, src/components/my/Profile/hooks.ts
* 마이페이지 api 연결합니다.
| Issue     |   #115     |
---
* 마이 페이지 api 연결
---
close #115 
---
=> 마이페이지 api 연결한다.

src/components/login/Auth/token.ts, src/pages/Login/OAuthPage.tsx
| Issue     |    #124    |
---
로그인 성공 후 uerId 절대값으로 설정
---
close #124 
---
=> 로그인 성공 후 uerId 절대값으로 설정한다.

src/components/login/button/LoginButton.tsx
| Issue     |    #126    |
---
로그인 버튼 클릭 시 redirectURI 절대 경로로 변경
---
close #126 
---
=> 로그인 버튼 클릭 시 redirectURI 절대 경로 설정

src/api/config.ts
| Issue     |    #128   |
---
URL에 dev가 포함되어있다면 VITE_API_URL_DEV 사용하도록, 아니라면 운영서버 사용
---
close #128 
---
=> dev환경에서 API 요청이 운영서버로 가는 이슈를 해결한다.

src/api/config.ts, src/api/useGetIdentificationInfo.ts, src/api/usePostKaKaoLogin.ts, src/pages/Login/OAuthPage.tsx
| Issue     |   #130     |
---
1. 로컬에서 절대 경로 반영 안 되어 config.ts 일부 수정
2. 개인 정보 API 세팅 
3. 개인 정보 API 호출하여 로그인 시 유저 본인의 마이페이지로 이동
작동 확인 완료
---
close #130 
---
=> 토큰에 추가된 userId를 반영하여 로그인 성공 시 유저 고유의 마이페이지로 리다이렉트 한다.

src/App.tsx, src/api/useGetVoteDetail.ts, src/components/common/Dialog/DialogProvider.tsx, src/components/vote-detail/ImageDetailModal/ImageDetailModal.tsx, src/components/vote-detail/ImageDetailModal/hooks.ts, src/components/vote-detail/ImageDetailModal/index.ts, src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx, src/components/vote-detail/Vote/VoteSection/VoteSection.tsx
* 이미지 상세 모달 제작
* 투표 상세에 연결
* 좋아요 버튼은 별도 이슈에서 해결합니다.
| Issue     |   #121     |
---
* 이미지 상세 모달에 image 배열, 현재 선택된 image의 id를 전달합니다.
* 현재 선택된 id를 보내는 이유는, 바로 그 쪽으로 이동시키기 위해
* VoteCardItem onClick에 핸들러 걸고, 좋아요 버튼에 e.stopPropagation 추가합니다. (하트 버튼 눌러도 모달 열림을 방지)
---
close #121 
---
=> 이미지 상세 모달을 제작한다.

src/api/useAddComment.ts, src/api/useGetComment.ts, src/components/comment-detail/CommentList/CommentList.tsx, src/components/comment-detail/CommentList/index.ts, src/components/comment-detail/hooks.ts, src/components/vote-detail/Comment/CommentList/CommentList.tsx, src/components/vote-detail/Comment/CommentList/hooks.ts, src/components/vote-detail/Comment/CommentSection/CommentSection.tsx, src/components/vote-detail/Input/CommentInput.tsx, src/components/vote-detail/Vote/VoteSection/VoteSection.tsx, src/pages/Vote/VoteCommentDetailPage.tsx, src/pages/Vote/VotePage.tsx, src/routes/routing.tsx
* 페이지네이션 구현
* 로딩 처리
| Issue     |   #142     |
---
* 페이지네이션 구현 및 로딩처리합니다.
---
close #142 
---
=> 댓글 페이지네이션을 구현한다.

src/api/useGetVoteDetail.ts, src/api/useGetVoteStatus.ts, src/api/useVote.ts, src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/CloseConfirmDialog.tsx, src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/hooks.ts, src/components/vote-detail/Top/ViteVerticalEllipsis/hooks.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx, src/components/vote-detail/Vote/VoteCard/hooks.ts, src/pages/Vote/VoteCommentDetailPage.tsx
* 투표 마감 시 베스트픽 처리합니다.
* 투표 여부에 따라 모달 description 분기처리합니다.
| Issue     |  #141      |
---
* 베스트픽 처리
* 분기 처리
---
close #141 
---
=> 투표 마감 시 베스트픽 처리한다.

src/api/useGetVoteDetail.ts, src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx
* 작성자일 때만 메뉴 버튼을 노출합니다.
| Issue     |   #147     |
---
* 분기 수정
---
close #147 
---
=> 메뉴 버튼이 작성자일 때만 노출하도록 수정한다.

src/components/common/Dialog/DialogProvider.tsx, src/components/common/Layout/DefaultLayout.tsx, src/pages/Vote/VotePage.tsx
* 이미지 상세 여백 생기는 문제 수정
* 플로팅 버튼 상이한 이슈 수정
* 투표 상세 컨텐츠 잘리는 이슈 수정
| Issue     |   #151 #152 #155     |
---
* 스타일 수정
---
close #151 
close #152 
close #155 
---
=> 플로팅 버튼 위치가 상이한 문제, 상세 컨텐츠가 잘리는 문제를 해결한다.

src/App.tsx, src/api/useGetMyInfo.ts, src/routes/routing.tsx
* `/` 접근 시에 케이스 별로 redirect 시킵니다 (history 지우기 위해 replace 옵션과 함께)
* 로딩처리도 추가합니다.
| Issue     |   #150     |
---
* 토큰 없음 -> `/onboarding`
* 토큰 있음 -> 내 정보 호출 -> 마이 페이지
---
close #150 
---
=> 리다이렉트 로직 작성한다.

src/App.tsx, src/api/config.ts, src/api/usePostGuestVote.ts, src/components/my/Profile/VoteList/ParticipatedVoteList/ParticipatedVoteList.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
* 게스트 투표 로그인 로직을 작성합니다.
---
* 토큰이 있음 -> `/votes` 요청
* 토큰이 없음 -> `/votes/guest` 요청
* 400 + INVALID_GUEST_HEADER인 케이스에 게스트 토큰을 받아오고 재요청합니다.
---
---
=> 게스트 로그인 로직을 작성한다.

src/App.tsx, src/api/useGetMyInfo.ts, src/api/useGetVoteStatus.ts, src/components/vote-detail/Vote/VoteCard/hooks.ts, src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx
=> status 호출 막기 + 리다이렉트 로직 수정

src/api/useGetVoteList.ts, src/api/usePostLogout.ts, src/components/settings/LogoutDialog/LogoutDialog.tsx
* 변경된 투표 리스트 변경 대응
* 로그아웃 api 추가 및 연결
| Issue     |   https://www.notion.so/portfolio-ohyunseong/1a9c0eb655cb80f8bff9df1621c6df63?pvs=4    |
---
* 변경 대응
* 추가 및 연결
---
resolve https://www.notion.so/portfolio-ohyunseong/1a9c0eb655cb80f8bff9df1621c6df63?pvs=4
---
=> 로그아웃 및 변경된 리스트 api에 대응한다.

src/api/usePostGuestVote.ts
=> 게스트 토큰이 있는 경우에만 헤더에 넣어둔다.

src/pages/OnBoarding/OnBoardingPage.tsx
| Issue     | #161      |
---
상단 공간 여백 줄이기
메인, 서브 텍스트 간격 줄이기
버튼 하부에서 여백 넓힘
---
---
=> 미반영된 온보딩 디자인을 반영한다. 

src/api/useKakaoShareUrl.ts, src/components/login/button/LoginButton.tsx, src/utils/cn/getEnvironment.ts
* 운영 카카오 관련 키값을 반영한다.
| Issue     |   #164     |
---
키 값 반영
---
close #164 
---
=> 운영 카카오 관련 키값을 반영한다.

src/api/config.ts, src/utils/cn/getEnvironment.ts
* import.meta.env를 참조하고 있어야하는데 다르게 참조하고 있어서 운영에서도 devapi에 요청함
| Issue     |   #173     |
---
* getIsDevelopment 수정
---
close #173 
---
=> 배포 환경 플래그 값을 잘못 참조하고 있는 것을 수정한다.

src/utils/cn/getEnvironment.ts
=> getIsDevelopment 로직 변경

src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/CloseConfirmDialog.tsx, src/components/vote-detail/Top/ViteVerticalEllipsis/hooks.tsx
| Issue     |  #176      |
---
컨펌 메시지 변경 사항 수정
---
close #176 
---
=> 투표 마감시 컨펌 메세지를 수정한다.

src/components/my/Profile/VoteList/MyVoteList/MyVoteList.tsx, src/components/my/Profile/VoteList/MyVoteList/hooks.tsx, src/components/my/Profile/VoteList/ParticipatedVoteList/ParticipatedVoteList.tsx, src/components/my/Profile/VoteList/VoteList.tsx, src/pages/my/MyPage.tsx
| Issue     |  https://www.notion.so/portfolio-ohyunseong/1a9c0eb655cb8028bb80fa483c9006dc?pvs=4     |
---
---
---
=> 게시물 여러개일 경우,  모든게시물이 다 안나옴

src/components/my/Profile/Profile.tsx, src/components/my/Profile/VoteList/MyVoteList/MyVoteList.tsx
| Issue     |   #166    |
---
이미지 사이즈 줄임
프로필 사진, 텍스트 중앙 정렬
---
close #166 
---
=> 마이페이지 미반영된 디자인을 대응한다.

src/api/usePostKaKaoLogin.ts, src/components/common/Dialog/Dialog.tsx, src/components/common/Layout/DefaultLayout.tsx, src/components/common/LoginDialog/LoginDialog.tsx, src/components/common/LoginDialog/hooks.ts, src/components/vote-detail/Input/CommentInput.tsx, src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/hooks.ts, src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx, src/pages/Login/OAuthPage.tsx, src/pages/Vote/VotePage.tsx
* 로그인 유도 다이얼로그 제작
* 로그인 + 리다이렉트 로직 작성
| Issue     |  https://www.notion.so/portfolio-ohyunseong/1aac0eb655cb80979872c9541d6a0c9b?pvs=4     |
---
* 로그인 유도 다이얼로그 제작
* 투표 상세로 리다이렉트 해야해서 로직 추가합니다.
* input, 플로팅 버튼, 마이페이지 클릭 시 다이얼로그 열립니다.
---
resolve https://www.notion.so/portfolio-ohyunseong/1aac0eb655cb80979872c9541d6a0c9b?pvs=4
---
=> 비회원일 경우 특정 버튼 클릭시, 로그인 팝업 띄우기

src/api/config.ts, src/components/common/TextInput/TextInput.tsx
* 댓글 작성 후에 댓글 칸 초기화가 안된다.
| Issue     |    https://www.notion.so/portfolio-ohyunseong/1a9c0eb655cb8009818eef5498a91d75?pvs=4   |
---
* TextInput에 value props 전달 누락;;;
* 필요없는 콘솔 값도 제거합니다.
---
resolve https://www.notion.so/portfolio-ohyunseong/1a9c0eb655cb8009818eef5498a91d75?pvs=4
---
=> 댓글 작성 후에 댓글 칸에 이전에 적었던 내용이 남아있다.

src/api/useGetVoteDetail.ts
* 비회원으로 투표하고, 상세를 다시 조회하면 투표한 값이 반영되지 않는다.
| Issue     |  https://www.notion.so/portfolio-ohyunseong/1aac0eb655cb8086a216f2faf6c21543?pvs=4     |
---
* 비회원으로 조회할 때에는 헤더에 게스트 토큰을 실어준다.
---
resolve https://www.notion.so/portfolio-ohyunseong/1aac0eb655cb8086a216f2faf6c21543?pvs=4
---
=> 비회원으로 투표하고, 상세를 다시 조회하면 투표한 값이 반영되지 않는다.

src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
=> 게스트 투표에도 로딩을 추가한다.

src/api/useGetVoteDetail.ts, src/components/login/Auth/token.ts, src/components/vote-detail/Input/CommentInput.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
* 게스트 로그인 로직 제거
* 게스트 투표 시도 시 로그인 다이얼로그를 띄운다.
---
---
---
=> 게스트 로그인 로직을 제거한다.

src/api/useGetVoteDetail.ts, src/components/login/Auth/token.ts, src/components/vote-detail/Input/CommentInput.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
=> 20250303_1414_deploy

src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx
* 투표 현황이 잘 보이지 않는 이슈를 해결한다.
| Issue     |   https://www.notion.so/portfolio-ohyunseong/1abc0eb655cb80799353fedd58e594a6?pvs=4    |
---
권한에 따른 분기 추가
---
resolve https://www.notion.so/portfolio-ohyunseong/1abc0eb655cb80799353fedd58e594a6?pvs=4
---
=> 투표 현황이 잘 보이지 않는 이슈를 해결한다.

src/components/common/BottomSheet/BottomSheet.tsx, src/components/common/Dialog/Dialog.tsx, src/components/common/Header/Header.tsx, src/components/common/LinkShareBottomSheet/LinkShareBottomSheet.tsx, src/components/vote-detail/Comment/CommentItems/CommentItem.tsx, src/components/vote-detail/Comment/CommentList/CommentList.tsx, src/components/vote-detail/Input/CommentInput.tsx, src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/CloseConfirmDialog.tsx, src/components/vote-detail/Top/ViteVerticalEllipsis/hooks.tsx, src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx, src/components/vote-detail/Vote/VoteResult/VoteResultItem.tsx, src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx, src/pages/NotFound/NotFoundPage.tsx, src/pages/Vote/VoteCommentDetailPage.tsx, src/pages/Vote/VotePage.tsx, src/pages/my/MyPage.tsx, src/pages/settings/SettingsPage.tsx, tailwind.config.js
| Issue     |   #200     |
---
Vote 페이지 내부 컴포넌트 간격 및 텍스트, 비율 수정
Vote 페이지 카드형 배경 삭제
헤더 자체 사이즈 조절, 뒤로가기 아이콘 사이즈 조절
Dialog, BottomSheet text 사이즈, 내용 수정
앞으로 다른 페이지에서도 헤더 내부 로고: `50px` 아이콘 사이즈: `medium`으로 맞춰서 가야할 것 같네요. 안 그러면 헤더 사이즈가 제각각이 되어버려요.
---
close #200 
---
=> 투표 게시글 페이지 QA에 대응한다.

src/components/common/Button/Button.tsx, src/pages/my/MyPage.tsx
| Issue     |   #202     |
---
사용 방법
`<Button buttonType="tertiary" size="jumbo" variant="solid"> 안녕하세요 </Button>`
tertiary: 색상 -400 추가
size: 기존의 large에서 높이 값이 다른 jumbo size 추가
이 버튼이나 사진 확대시 투표 버튼이나 딱 한 번씩만 사용될 것 같아서 굳이 컴포넌트로 작성하지 않고 그냥 요소로 넣는 게 좋을 것 같다는 생각이 드네요. 의견 코멘트 달아주시고 같은 생각이시면 pr close 하겠습니다
---
close #202 
---
=> 버튼 디자인 추가 대응

.github/workflows/git-push.yml
=> push workflow 수정

src/components/common/Switch/Switch.stories.tsx, src/components/common/Switch/Switch.tsx, src/components/common/Switch/index.ts, src/index.css
* secondary 색상 추가
* switch 컴포넌트 작성
| Issue     |   #218     |
---
* switch 컴포넌트는 사용처에서 완전히 컨트롤하는 제어 컴포넌트로 만들었습니다.
* 스토리북 예제로 사용법 확인해주시면 됩니다!
```ts
interface SwitchProps {
size?: 'medium' | 'small'; // default 값은 medium 입니다. (optional)
disabled?: boolean; // 컨트롤 가능 여부 (optional)
checked: boolean; // 초깃값 전달 (required)
onChange: (checked: boolean) => void; // 핸들러 전달 (required)
className?: string; // 스타일 오버라이딩을 위함 (optional)
name?: string; // Form 형식에서 값을 전달할 때 사용 (optional)
value?: string; // Form 형식에서 키 값으로 사용 (optional)
}
```
---
close #218 
---
=> switch 컴포넌트를 제작한다.

src/components/common/Label/AnimatedLabel.tsx, src/components/common/Label/Label.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx, tailwind.config.js
| Issue     |   #209     |
---
사용 방법
```
<Label variant=“solid” color=“isPicked”>뽀또픽</Label>
<Label variant=“outline” color=“isProgress”>진행중</Label>
<Label variant=“outline” color=“voteEnded”>투표 종료</Label>
```
https://github.com/user-attachments/assets/bf7b25d3-3cab-4f78-9d21-662a657a7760
사용 방법
```
<AnimatedLabel color="accent">
<Icon name="MedalWhite" size="small" />
<span className="pl-[3px]">베스트픽!</span>
</AnimatedLabel>
<AnimatedLabel color="primary">뽀또 PICK</AnimatedLabel>
```
---
close #209 
---
=> 추가된 라벨 컴포넌트에 대응한다.

src/api/useKakaoShareUrl.ts, src/components/login/button/LoginButton.tsx, src/hooks/useKakaoLogin.ts
* develop, production 환경의 키 값이 통일됨에 따라 분기를 제거합니다.
* VITE_KAKAO_PROD_JAVASCRIPT_APP_KEY, VITE_KAKAO_PROD_CLIENT_ID는 deprecate 처리합니다.
* 환경변수 파일에서 지우셔도 됩니다!
| Issue     |  #231      |
---
* 키 값 통일
* 요거 배포되고 운영까지 나가면 버셀에도 반영 예정
---
close #231 
---
=> 카카오 관련 환경변수를 통일한다.

src/components/common/RadioButton/RadioButton.stories.tsx, src/components/common/RadioButton/RadioButton.tsx, src/components/common/RadioButton/RadioGroup.tsx, src/components/common/RadioButton/index.ts, src/components/common/RadioGroup/RadioGroup.stories.tsx, src/components/common/RadioGroup/RadioGroup.tsx, src/components/common/RadioGroup/index.ts, src/components/common/Switch/Switch.stories.tsx
* 단일 RadioButton 컴포넌트 제작
* RadioGroup 제작
* 스토리북 예제 작성
| Issue     |    #219    |
---
* 단일 -> RadioButton
* 그룹 -> RadioGroup
---
close #219 
---
=> RadioButton, RadioGroup 컴포넌트를 제작한다.

src/api/useGetVoteDetail.ts, src/components/common/Dialog/Dialog.tsx, src/components/common/Dialog/DialogProvider.tsx, src/components/vote-detail/ImageDetailModal/ImageDetailModal.tsx, src/components/vote-detail/ImageDetailModal/hooks.ts, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
* 좋아요 버튼 추가
* 상단 이미지 슬라이더 추가
* 이미지 너비 안 맞는 문제 수정
* DialogProvider 스타일 수정
| Issue     |  #224      |
---
* 2차 MVP 반영 작업
---
close #224 
---
=> 이미지 상세 모달 2차 MVP 반영한다.

src/api/useCancelVoted.ts, src/api/useGetMyInfo.ts, src/api/useGetVoteDetail.ts, src/api/useGetVoteStatus.ts, src/components/vote-detail/ImageDetailModal/ImageDetailModal.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx, src/components/vote-detail/Vote/VoteCard/hooks.ts, src/components/vote-detail/Vote/VoteResult/hooks.ts
| Issue     |   #237     |
---
API 변경 점 voted -> voteId로 변경하여 투표 UI 변경되지 않는 점 수정
투표 취소 구현
단일 투표 동작 잘 됨.
복수 투표 시 아래 사진과 같이 동작
테두리와 라벨이 사진들중 먼저 선택한 하나에만 적용되는 듯 하는데 이 부분 체크 부탁드립니다.
---
close #237 
---
=> 투표 취소 기능을 구현한다.

src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx, src/components/vote-detail/Vote/VoteResult/hooks.ts
| Issue     |  #240    |
---
투표 현환 더보기 구현 (결과 3개 이상일 시 더보기 버튼)
---
https://github.com/user-attachments/assets/e01f6d39-beb7-41e1-abd0-332bbac7399d
close #240 
---
=> 투표 현황의 더보기 버튼을 구현한다.

src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
| Issue     |    #247    |
---
투표된 이미지는 투표 취소 API만 호출하고, 그렇지 않은 경우에는 투표 API를 호출하도록 변경
(불필요한 voteMutate 호출 삭제)
---
close #247 
---
=> 투표 취소 API 호출 시 투표 API가 함께 호출되지 않도록 반영한다.

src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx, src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx, src/components/vote-detail/Vote/VoteCard/hooks.ts
* 투표 반영되지 않는 문제 해결
* 마감된 투표도 클릭 시 서버 요청하는 문제 수정 -> 토스트 띄우기
* 라벨 겹쳐서 보이는 문제 해결
* 투표 취소 로딩 추가
| Issue     |    #239    |
---
* 베스트픽 배열 반환하는 커스텀 훅 제작 (공동 득표 대응 위해)
* 로딩 추가
* 라벨 노출 조건 수정
---
close #239 
---
=> 투표 결과가 반영되지 않는 문제를 해결한다.

src/hooks/useNicknameNavigation.tsx
| Issue     |   #244     |
---
닉네임 클릭 시 해당 유저 마이페이지로 이동
홈페이지 구현 후 홈, 게시글 연동하면서 수정 가능성 있습니다.
---
close #244 
---
=> 닉네임 클릭 시 해당 닉네임을 유저의 마이페이지로 이동하는 커스텀 훅을 제작한다.

src/api/useGetFeed.ts, src/components/home/HomeImages/ImageItem.tsx, src/components/home/HomeImages/ImageList.tsx, src/components/home/HomeInfo/HomeInfo.tsx, src/components/home/HomeSection/HomeSection.tsx, src/components/home/HomeTaskCheck/HomeTaskCheck.tsx, src/components/vote-detail/Comment/CommentItems/CommentItem.tsx, src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx, src/hooks/useNicknameNavigation.tsx, src/pages/Home/Home.tsx
| Issue     |   #246     |
---
홈페이지 API 연결 완료.
홈에서 게시글 이미지 클릭 시 해당 shareUrl가진 상세 게시글로 이동
홈에서의 nickname, 상세 게시글 닉네임, 댓글 닉네임 클릭 시 해당 유저 마이페이지로 이동
---
close #246 
---
=> 홈 페이지 API를 연동한다.

src/components/my/Profile/VoteList/MyVoteList/MyVoteList.tsx, src/components/my/Profile/VoteList/ParticipatedVoteList/ParticipatedVoteList.tsx, src/components/my/Profile/VoteList/Tab/Tab.tsx, src/components/my/Profile/VoteList/VoteList.tsx, src/components/settings/Menu/Menu.tsx, src/components/settings/hooks.tsx, src/pages/PrivacyPolicy/PrivacyPolicyPage.tsx, src/pages/Terms/TermsPage.tsx, src/pages/my/MyPage.tsx, src/routes/routing.tsx
* 누락된 스타일 반영
* 내 페이지에서만 '투표 올리기' 버튼 노출되도록 수정
* 내가 참여한 투표 공유 아이콘 제거
| Issue     |  #227      |
---
* 이용약관, 개인정보처리방침 개발은 별도 페이지에서 진행한다.
---
close #227 
---
=> 마이페이지, 설정페이지 2차 MVP를 반영한다.

src/api/useGetFeed.ts, src/components/home/HomeSection/HomeSection.tsx, src/components/home/hooks.ts, src/pages/Home/Home.tsx, src/types/feed.ts
| Issue     |  #253      |
---
홈페이지 페이지네이션 구현
ImageList에서 Suspense 없이 렌더링하려니까 404 에러가 뜨더라고요.
그래서 Suspense로 감싸고 데이터가 로딩될 때 에러 없이 표시되도록 했습니다.
---
close #253 
---
=> 홈페이지 페이지네이션 기능을 구현한다.

src/components/home/HomeImages/ImageList.tsx, src/components/home/hooks.ts
| Issue     |  #261      |
---
cleanup 함수에서 IntersectionObserver 해제하여 중복 호출 방지
기존 shareUrl 불러오기 위해 사용했던 불필요한 useVoteDetail API 호출 제거
---
close #261 
---
=> 피드 API 호출 관련 QA를 반영한다.

src/pages/Home/Home.tsx, src/pages/Login/OAuthPage.tsx, src/pages/NotFound/NotFoundPage.tsx, src/pages/Vote/VoteCommentDetailPage.tsx, src/pages/Vote/VotePage.tsx, src/pages/my/MyPage.tsx
| Issue     |  #259      |
---
진행중
---
close #259 
---
=> 2차 MVP QA 페이지 이동을 설정한다.

src/api/useDeleteComment.ts, src/components/vote-detail/Comment/DeleteCommentDialog/hooks.ts
* 댓글 삭제 후 바로 반영되지 않는 문제를 해결한다.
| Issue     |   #256     |
---
* useDeleteComment 사용처에서 작성한 onSuccess가 오버라이딩되어, 내부의 쿼리 무효화 로직을 덮어썼음
* onSuccess 로직을 사용처로 전부 옮긴다.
---
close #256 
---
=> 댓글 삭제 후 바로 반영되지 않는 문제를 해결한다.

src/components/common/Layout/DefaultLayout.tsx
* 바텀 네비게이션이 컨텐츠 가리는 문제를 해결한다.
| Issue     |  #266      |
---
* 임시방편으로 네비게이션 너비만큼 pb 준다.
* 좋은 방법이 아니라 레이아웃 개편 이슈에서 리팩토링한다.
---
close #266 
---
=> 바텀 네비게이션이 컨텐츠 가리는 문제를 해결한다.

src/components/common/Navigation/hooks.tsx, src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx, src/pages/Home/Home.tsx, src/pages/Login/OAuthPage.tsx, src/pages/NotFound/NotFoundPage.tsx, src/pages/OnBoarding/OnBoardingPage.tsx, src/pages/Vote/VoteCommentDetailPage.tsx, src/pages/my/MyPage.tsx, src/routes/routing.tsx
| Issue     |    #265    |
---
기본 도메인 접속 시
비회원: onboarding 으로 이동
회원: home 으로 이동
로그인 시
home으로 이동
로그인 후 온보딩 접근시
home으로 이동
---
close #265 
---
=> 토큰 유무에 따른 라우팅 경로를 설정한다.

src/components/home/HomeImages/ImageItem.tsx, src/components/home/HomeImages/ImageList.tsx, src/components/home/HomeInfo/HomeInfo.tsx, src/components/home/HomeSection/HomeSection.tsx, src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx, src/components/vote-detail/Top/VoteTopSection/VoteTopSection.tsx, src/components/vote-detail/Top/VoteTopSection/index.ts, src/pages/Home/Home.tsx, src/pages/Vote/VotePage.tsx
* 알림 버튼 클릭 시 토스트 제공
* 라우팅 이벤트 핸들러 몇 가지 수정
* VoteTopSection 제거 (div만 감싼 컴포넌트였음)
| Issue     |   #270     |
---
* 토스트 로직 추가
* 피드에서 프로필 제외 아무곳이나 클릭하면 상세로 이동하도록 수정
* VoteTopSection 제거
---
close #270 
---
=> 알림 버튼 클릭 시 토스트를 제공한다.

src/components/vote-detail/ImageDetailModal/ImageDetailModal.tsx
| Issue     |    #273    |
---
ImageDetailModal 상단 이미지 규격 유지하며 스크롤 생기도록 수정
---
https://github.com/user-attachments/assets/6bc8f251-ce03-4273-8372-b5121fb42d12
close #273 
---
=> 사진 확대 시 상단 사진배열 너비 고정후 드래그 하게 할 수 있도록 수정한다.

src/pages/Home/Home.tsx
| Issue     |   #275     |
---
isUserLoading을 확인하지 않아도, myInfo가 null이거나 id가 없으면 onboarding으로 이동하도록 세팅하였습니다.
myInfo가 undefined 처리되어 이동하지 않았던 것이었음.
---
close #275 
---
=> 비회원이 기본 도메인 접근 시 onboarding으로 가도록 한다.

src/components/settings/hooks.tsx
* 피드백 주기 메뉴를 추가한다.
| Issue     |    #277    |
---
* 노션 링크 걸어두고, 새 탭으로 이동하도록 로직 작성
---
close #277 
---
=> 피드백 주기 메뉴를 추가한다.

src/components/vote-detail/ViteVerticalEllipsis/hooks.tsx
* 마감된 투표 투표마감 버튼 비활성화
| Issue     |   https://www.notion.so/portfolio-ohyunseong/1aec0eb655cb80049d19faef79084b45?pvs=4    |
---
* 토스트 제공한다.
---
resolve https://www.notion.so/portfolio-ohyunseong/1aec0eb655cb80049d19faef79084b45?pvs=4
---
=> 마감된 투표 투표마감 버튼 비활성화

src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx, src/components/vote-detail/Vote/VoteResult/hooks.ts
| Issue     |  #281      |
---
| Issue     |   https://www.notion.so/portfolio-ohyunseong/1a7c0eb655cb805d840bff8f260af749?v=1a7c0eb655cb802d8d28000c64063438&p=1abc0eb655cb804da1b5e13647a6cf94&pm=s    |
---
게시글 작성자는 투표를 하지 않아도 투표 현황을 확인할 수 있도록 수정.
---
resolve https://www.notion.so/portfolio-ohyunseong/1a7c0eb655cb805d840bff8f260af749?v=1a7c0eb655cb802d8d28000c64063438&p=1abc0eb655cb804da1b5e13647a6cf94&pm=s
close #281 
---
=> 해당 게시글의 Author일 시 투표 현황을 항상 보여준다.

src/components/vote-detail/Vote/VoteResult/VoteResultItem.tsx
| Issue     |   #291     |
---
사진 이름 란 사이즈 넉넉하게 늘리고 현황 시작점 좌측 여백값 없애서 기존 ui에서 크게 벗어나지 않도록 수정했습니다.
---
close #291 
---
=> 투표 결과 바 UI를 개선한다.

src/pages/Vote/VotePage.tsx
| Issue     |   #293     |
---
로고 클릭 시 경로 '/home' -> '/' 로 수정
---
#293 
---
=> 투표 디테일 페이지 헤더 로고 클릭 시 경로를 수정한다.

src/api/useGetVoteList.ts, src/components/common/Toast/Toast.tsx
=> 누락된 쿼리키를 추가하고, 토스트 UI를 수정한다.
